agent_urdf: humanoid/humanoid.urdf
const_seg_lens: true
ctrl_rate: 25
custom_pose: null
data_splits: train,val
dataset: h36m_25fps
dataset_root: datasets 
drawRef: false
exp_name: S9_Waiting_1
floor_pent_reduce: 0.0
frame_offset: 200
friction: 0.9
height_adjust: 0
input_traj: ./saved_traj/h36m_S9_Waiting_1.npy
joint_weights: 1,1,10,1,1,3,1,10,1,1,3,1
joints_enforce: null
kds: 100,10,50,50,40,40,30,50,50,40,40,30
kps: 1000,100,500,500,400,400,300,500,500,400,400,300
log: true
lower_feet_to_height: -0.001
mass_scale: 1.0
match_init_contact: true
max_ext_force: 0
maxiter: 200
movement: Waiting_1
nCPUs: 40
num_windows: 8
opt_eul: true
popsize: 100
pose_format: mscoco_foot
rotate_ankles: false
seed: 999
sigma: 0.01
sim_freq: 1000
subject: S9
useGUI: false
vid_dir: ./optimized_videos
video_name: null
w_acc: 1.0e-10
w_chest: 0.0
w_com: 20.0
w_com_orn: 1.0
w_comv: 0.5
w_feet: 1.5
w_head: 0.0
w_joint: 1.0
w_vel: 0.0005
window_length: 0.5
write_video: false
